---
title: "Cronograma Semanal"
subtitle: "Atividades e eventos"
---

Abaixo você encontrará o cronograma semanal dos materiais, assuntos e tarefas a serem realizadas ao longo das 15 semanas do Pesquisa pra Elas. Alguns materiais serão atualizados ao longo do projeto, então podem não estar disponíveis no momento.

-   Na aba **Entenda**, você encontrará o link dos materiais que devem ser estudados ao longo da semana e que serão importantes para completar as tarefas e demais atividades.

-   Na aba **Explore**, você encontrará algumas sugestões do time de links úteis caso tenha interesse em explorar mais sobre o tópico.

-   Na aba **Entregue**, estão listadas as datas de disponibilidade das tarefas e seus prazos.

| Semana |   Data    |                  Assunto                   | Entenda                                                                  | Explore                                        | Entregue                                |
|:---------:|:---------:|:---------:|-------------------|-----------|-----------|
|   1    |   04/05   |          Reunião de Boas-vindas!!          |                                                                          |                                                |                                         |
|   1    |   06/05   | Apresentações + Ferramentas de organização |                                                                          |                                                | Tarefa 1 Liberada                       |
|   2    |   12/05   |    Introdução à metodologia científica     | [Curso APICE](https://apice.febrace.org.br/)                             | [Guia Cientista Beta](Guia%20Cientista%20Beta) | Entrega Tarefa 1 + Termo de Compromisso |
|   2    | Até 19/05 |         Call mentoradas & mentoras         |                                                                          |                                                |                                         |
|   3    |   19/05   |   Escolha do tema e problema da pesquisa   |                                                                          |                                                | Tarefa 2 liberada                       |
|   3    |   24/05   |              Café com Ciência              |                                                                          |                                                |                                         |
|   3    |   25/05   |                  Palestra                  |                                                                          |                                                |                                         |
|   4    |   26/05   |       Entendendo o Plano de Pesquisa       |                                                                          |                                                | Entrega Tarefa 2                        |
|        |           |                                            | **Obs: Próximas semanas serão liberadas conforme andamento do programa** |                                                |                                         |

###  Café com Ciência 

Estamos muito animadas para o nosso **Café com Ciência** ! Vamos nos encontrar a cada duas semanas, conforme o cronograma acima, para revisar os assuntos estudados nas semanas anteriores, tirar dúvidas, nos conhecer melhor e trocar experiências!!

### Tarefas

Por favor, lembre-se de entregar todas as tarefas até as 23h59 do domingo seguinte à sua liberação. No mesmo dia, a tarefa da semana seguinte será disponibilizada. Se ocorrer algum imprevisto e você não puder concluir a tempo, não hesite em nos contatar. Estamos aqui para ajudar!
